In [1]:
import numpy as np

In [11]:
dec_coords = 9*np.random.rand(10, 2) + 1
dec_coords

array([[1.64414156, 8.57685741],
       [7.8341755 , 2.14224077],
       [8.39237385, 3.8319447 ],
       [6.45415872, 5.33590858],
       [4.83257727, 1.20702503],
       [8.06923288, 4.41029622],
       [2.6004856 , 7.89520298],
       [5.94490698, 2.61158194],
       [9.67820156, 9.14879203],
       [1.60705781, 6.12018677]])

In [12]:
r = np.sqrt(dec_coords[:, 0]**2 + dec_coords[:, 1]**2)
theta = np.arctan2(dec_coords[:, 1], dec_coords[:, 0])

In [13]:
polar_coords = np.column_stack((r, theta))
polar_coords

array([[ 8.73302264,  1.38139885],
       [ 8.12179175,  0.26692289],
       [ 9.22581915,  0.42832761],
       [ 8.37425131,  0.69083425],
       [ 4.98103528,  0.24476066],
       [ 9.19582688,  0.50019604],
       [ 8.31244581,  1.25261214],
       [ 6.49324874,  0.41391805],
       [13.31795709,  0.75728586],
       [ 6.32766315,  1.31401023]])

In [19]:
n = np.random.randint(1, 10)
m = np.random.randint(1, 10)
matrix = 9*np.random.rand(n, m) + 1
matrix

array([[1.45921304, 6.00055794, 4.39595729, 2.79779945, 7.78383982],
       [7.53988762, 7.16227884, 7.53703902, 4.3507132 , 4.07463362],
       [5.59857892, 3.82203844, 4.74466279, 7.47265386, 1.45501164],
       [6.21965154, 1.90256471, 7.06068966, 7.13237322, 4.34525112],
       [7.92324322, 3.47913783, 6.57006698, 5.56913313, 1.46134064],
       [6.41288903, 9.11630222, 9.74953443, 2.48660389, 4.52990049],
       [3.42303132, 9.6700192 , 3.6678107 , 2.42783128, 8.13630897],
       [5.46972014, 9.63335347, 2.85510554, 5.51013239, 6.95769612]])

In [20]:
rank = np.linalg.matrix_rank(matrix)
rank

5

In [26]:
matrix = np.loadtxt('matrix.txt')
u,s,v=np.linalg.svd(matrix, compute_uv=True)
print(f"u = {u}")
print(f"s = {s}")
print(f"v = {v}")

u = [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
s = [9.508032   0.77286964]
v = [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
